export const historico = [
  {
    sigla: "SIS000",
    disciplina: "Algoritmos e Lógica de Programação",
    periodo: "20242",
    aprovado: "Aprovado(a)",
    mediaFinal: "7.50",
    frequencia: "80%",
    qtdFaltas: 16,
    observacao: "Aprovado por Nota e Frequência",
  },
  {
    sigla: "SIS001",
    disciplina: "Estruturas de Dados",
    periodo: "20241",
    aprovado: "",
    mediaFinal: "4.00",
    frequencia: "80%",
    qtdFaltas: 16,
    observacao: "Em Curso",
  },
  {
    sigla: "SIS002",
    disciplina: "Matemática Discreta",
    periodo: "20242",
    aprovado: "",
    mediaFinal: "4.00",
    frequencia: "80%",
    qtdFaltas: 16,
    observacao: "Em Curso",
  },
  {
    sigla: "PCL002",
    disciplina: "Prática de Programação",
    periodo: "20232",
    aprovado: "Aprovado(a)",
    mediaFinal: "8.80",
    frequencia: "80%",
    qtdFaltas: 16,
    observacao: "Aprovado por Nota e Frequência",
  },
  {
    sigla: "PDT100",
    disciplina: "Programação de Dispositivos Móveis",
    periodo: "20241",
    aprovado: "",
    mediaFinal: "4.00",
    frequencia: "80%",
    qtdFaltas: 16,
    observacao: "Em Curso",
  },
  {
    sigla: "PDI100",
    disciplina: "Inteligência Artificial",
    periodo: "20232",
    aprovado: "",
    mediaFinal: "4.00",
    frequencia: "80%",
    qtdFaltas: 16,
    observacao: "Em Curso",
  },
  {
    sigla: "PDI001",
    disciplina: "Projetos Integradores",
    periodo: "20241",
    aprovado: "",
    mediaFinal: "--",
    frequencia: "80%",
    qtdFaltas: 16,
    observacao: "Em Curso",
  },
];
